main.yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -10,33 +10,34 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      # Шаг 1: Клонирование репозитория
+      # Step 1: Clone the repository
       - name: Checkout code
         uses: actions/checkout@v2
 
-      # Шаг 2: Установка Node.js
+      # Step 2: Set up Node.js
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
           node-version: 20
 
-      # Шаг 3: Установка зависимостей и сборка Angular-приложения
+      # Step 3: Install dependencies and build the Angular app
       - name: Build Angular app to prod
         run: |
           npm install
           npm run build:prod
 
-      # Шаг 4: Очистка временных директорий
+      # Step 4: Clean up worktree and detach prod
       - name: Clean up worktree
         run: |
           git worktree prune
           rm -rf .git/worktrees/*
+          git branch -D prod || true
 
-      # Шаг 5: Отладка worktree (опционально)
+      # Step 5: Debug worktree (optional)
       - name: Debug worktree
         run: git worktree list
 
-      # Шаг 6: Деплой на GitHub Pages
+      # Step 6: Deploy to GitHub Pages
       - name: Deploy to GitHub Pages
         uses: JamesIves/github-pages-deploy-action@v4
         with:
